excluded:
  - Carthage

line_length: 200

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded:
  - r
  - g
  - b
  - a
  - x
  - y
  - id
  max_length: 100
  
type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
    
function_body_length:
  warning: 100
  error: 200

cyclomatic_complexity:
  warning: 15
  error: 20
